### ISSUE TITLE
Monitor/Debugger GUI text color

### ISSUE THREAD

**Issue by Sasatari** [atarimacosx/Atari800MacX#1]
The text color in the Monitor and Debugger GUI is black on dark gray, which is hard to read. I generally like the dark Theme, but the text should be in a somewhat better readable color, like blue or green.
![monitor_debuggergui](https://user-images.githubusercontent.com/17954889/50689124-a6854980-1028-11e9-9723-d39294ef1f91.jpg)

**Comment by pedgarcia** [comment]
I agree it is hard to read. Are you using Mojave with the Dark Theme set?

**Comment by atarimacosx** [comment]
I've fixed the Monitor Debugger windows for Mojave Dark Mode, as well as Disk Editor windows.
The only Dark Mode issue that still needs to be fixed is the lock image for the disk drives in the Media Status Window.  Right now it loads a lock off image from disk.  It may be better to create the image programmatically, with the dark background color.

**Comment by atarimacosx** [comment]
I should have said I "fixed" it by using standard named colors like textColor and labelColor, that get switched automatically with Dark Mode.  This was the simplest change.  This means the monitor,  memory windows, etc. have white text on black background for the Dark mode.  Another remaining issue may be with the red text that is used to show changed register or memory values.  It is not especially readable in text mode.

**Comment by atarimacosx** [comment]
Sorry for all the messages, but perhaps red text on a white background for the changed memory and registers?

**Comment by pedgarcia** [comment]
Should be good that way.

**Comment by atarimacosx** [comment]
Changed text color for changed registers/memory to red on white background, and also changed highlight color in disassembly table, as well as lock icon unlocked  mode.
I believe that catches all the Dark mode issues, please reopen if that isn't true.
