### ISSUE TITLE
1020 Plotter Support

### ISSUE THREAD

**Issue by savetz** [atarimacosx/Atari800MacX#10]
Atari 1020 Plotter emulation seems to be broken :(

**Comment by pedgarcia** [comment]
Hey Kevin, can you give me an example on how to test it? I just tried a simple LIST"P:" and it was "printing" a basic listing, but I believe you tried some graphics, right?

**Comment by savetz** [comment]
Since submitting the ticket, I did get it to plot with the Atari demos.

However when I plot with Renderific, it doesn't work in the emulator. The same code works on a real Atari. https://github.com/savetz/Renderific/blob/master/renderific-10.atr 

I'm willing to admit the problem is my code, but something is weird when it works on real hardware but not in the emulator.

**Comment by pedgarcia** [comment]
@savetz It has been a while (almost 1 year!) but looks like the recent changes in the emulator, including a new version of SDL made the plotter work, or at least I assume that is the case.

Using the upcoming version 5.0.4, this is what I've got if your program:

![1020atariplotter](https://user-images.githubusercontent.com/3932415/82744946-00390180-9d4d-11ea-956a-1cde5b38d2b3.png)

Is that what we should expect?

Cheers

Paulo

**Comment by savetz** [comment]
That looks beautiful. Well done.

**Comment by pedgarcia** [comment]
Glad it is working as expected :) We don't know how that got fixed but I know when you send your disk image I tried (last year) and it wasn't working indeed :).

Fixed by luck is the best :)
