### ISSUE TITLE
Invalid Donnation URL

### ISSUE THREAD

**Issue by peterdell** [atarimacosx/Atari800MacX#12]
Me and a friend of mine would like to send a donation. But the donation on the web site and in the emulator points to Kagi, which is no longer in business.

http://order.kagi.com/?6FBTU&lang=en => This site cannot be reached.

In case donations are no longer required, the links should be removed from the site and the menu,

**Comment by pedgarcia** [comment]
I am proposing for the next update to link to Internet Archive donation page, but I couldn't get on hold of Mark yet. If you want to proceed with your donation to the Archive, you can use this link: https://archive.org/donate/

THanks

**Comment by atarimacosx** [comment]
This is fixed in Version 5.0.2, with a link to donate to the Internet Archive.

**Comment by peterdell** [comment]
Verfied, OK.
