### ISSUE TITLE
Fullscreen Mode wrong on Mac OS X Catalina

### ISSUE THREAD

**Issue by Sasatari** [atarimacosx/Atari800MacX#14]
When running in Fullscreen-mode under OS X Catalina, the display is showing only the lower part of the Atari-screen. The lower half of the display is just black. In windowed mode all is working correctly so far.

**Comment by pedgarcia** [comment]
I won't be able to update to Catalina for a few more weeks (important software incompatibility) - I will try to see what is going on then.

**Comment by atarimacosx** [comment]
This is fixed in Version 5.0.2 by update the SDL Framework to the newest version, and allowing for high DPI when opening a SDL Window.
