### ISSUE TITLE
Paths with Umlauts don´t work

### ISSUE THREAD

**Issue by Sasatari** [atarimacosx/Atari800MacX#19]
On German systems, ATRs which are in Folders with Umlauts ("ä", "ö", "ü") in the name can´t be opened,

Florian D. has a folder "Veröffentlicht" ("released") and figured this one out. I totally can reproduce it.

**Comment by atarimacosx** [comment]
Is this working for you now with 5.3+?

**Comment by Sasatari** [comment]
Meanwhile we´re on 5.4.1 and here it works for me.
Tried many Umlauts and spaces, no problem.

**Comment by polluks2** [comment]
@Sasatari You may close this issue.
