### ISSUE TITLE
Cannot load disk images

### ISSUE THREAD

**Issue by jtsom** [atarimacosx/Atari800MacX#20]
All of a sudden, Atari800MacX 5.3 does not want to load a disk image. Doesn't matter what the format is (Dos 2.5, DOS Xl, etc.) or model I'm emulating (800, 800XL, 130XE), when I try to load a disk image, it crashes with the error
 

![](https://atariage.com/forums/uploads/monthly_2020_09/image.png.f5a7ac1cee5bc6e5601e8f7210d7addb.png)

Not sure what happened. Not sure if it helps, but clicking on the Monitor button shows the PC is on page zero somewhere:

![](https://atariage.com/forums/uploads/monthly_2020_09/image.png.a0e586802f9296ef7cfa24e865818c6d.png)

These are the settings on the "Atari" tab:
![image](https://user-images.githubusercontent.com/13488/92648458-6ffcd900-f2b7-11ea-938b-6f0b61db9aee.png)

**Comment by markgrebe** [comment]
@jtsom , it looks like it is the D: Patch.  If you turn that off, it should get rid of your issue.  That's not a patch that the Linux Atari800 supports, in fact I don't remember where I got it from over 10 years ago.  I may have made a mistake merging it into the new Atari800 core, or it may just be incompatible.  I'll try to look before the next release.

**Comment by atarimacosx** [comment]
@jtsom, did turning of D: patch fix this for you?

**Comment by jtsom** [comment]
Yes I did. After I turned it off everything was working fine.
