### ISSUE TITLE
double press on keyboard

### ISSUE THREAD

**Issue by MisfitMovies** [atarimacosx/Atari800MacX#8]
hey there thanks so much for updating Atari800MacX. works super well overall. 

Can't find a reference for my issue. I find in games like Ghostbusters and Hacker that pressing a key on the keyboard makes 2 versions of the letter come up. I've tried with the MacBook Pro keyboard and a usb one. If I press super fast its just one but difficult to pull off.

A note is that it doesn't do it in Atari basic or text adventures.

Video example here: https://vimeo.com/312246393

I've messed around with the Mac keyboard settings (delay etc.) but no difference.

**Comment by markgrebe** [comment]
Try turning on "Use International Keyboard Translation" on the Atari Tab of the Preferences for the Program.  I believe this will fix your issue, at least it fixed the issue for me and for someone else who had the issue.  libSDL did major changes on how they handle keypresses.  I am thinking of removing this option and making it always on in Version 5.0.1 which will come out soon.

**Comment by MisfitMovies** [comment]
Perfect that worked. Thank you!  One more note, how do I donate? link doesn't work.
