### ISSUE TITLE
Control-J

### ISSUE THREAD

**Issue by savetz** [atarimacosx/Atari800MacX#9]
Control-J is supposed to toggle keyboard joysticks on/off; this doesn't seem to work anymore. (Doing it by choosing Enable Keyboard Joysticks from Control menu is OK.)

**Comment by pedgarcia** [comment]
I have a fix for this, but I'd like to confirm the change with Mark. Meanwhile, I might release a beta 5.0.2 from my fork to be tested.

**Comment by atarimacosx** [comment]
This is fixed in Version 5.0.2.
